name: Open Webpage Echo Message

on: workflow_dispatch
  ##schedule:
    ##- cron: "0 0 * * *"

jobs:
  open_webpage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Open webpage
      run: google-chrome-stable --headless --disable-gpu --no-sandbox --virtual-time-budget=180000 https://www.kaggle.com/aryashah2k

    - name: Wait for 3 minutes
      run: sleep 10

    - name: Print completion message
      run: echo "Webpage visited successfully."

    
